### ISSUE TITLE
UML Use Case Diagrams

### ISSUE THREAD

**Issue by cfulton5** [victoriarouton/Hermes#45]

**Comment by cindyherrera** [comment]
Use case diagram:
- Shows relationships between cases and actors and gives functional system overview
- Do not show chronological sequence in which services are rendered
- Useful when presenting because it highlights roles that interact with system and the functionality provided by the system


Consists of 4 objects:
- Actor
- Use case
- System 
- Package

**Comment by anaqvi72** [comment]
![useCase1.PNG](https://images.zenhubusercontent.com/6007ac8e76e715907a8c2d48/41686211-9264-4272-bfac-c65fd3acf072)

**Comment by cindyherrera** [comment]
![usecase1.jpg](https://images.zenhubusercontent.com/601259e7adb9f70b35b93953/01b77503-bc5d-451c-8cb3-def7e26873a8)

**Comment by cindyherrera** [comment]
![usecase2.jpg](https://images.zenhubusercontent.com/601259e7adb9f70b35b93953/86d82811-f691-4ad1-a378-cf0a427257b5)
